config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :tests
  resources :answers
  resources :questions
  resources :coincidences
  resources :articles
  resources :animals
  resources :articlecats
  resources :animalcats
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
	has_many :coincidences
	belongs_to :animalcat 
	has_many :articles 
	has_many :tests
end

app/models/animalcat.rb
class Animalcat < ApplicationRecord
	has_many :animals
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	has_many :results
	has_many :tests, through: :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :animal
	belongs_to :articlecat
end

app/models/articlecat.rb
class Articlecat < ApplicationRecord
	has_many :articles
end

app/models/coincidence.rb
class Coincidence < ApplicationRecord
	belongs_to :animal
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :test
	belongs_to :answer
end

app/models/test.rb
class Test < ApplicationRecord
	belongs_to :animal
	belongs_to :user
	has_many :results
	has_many :answers, through: :results
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tests
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :description, :price, :animal_id, :articlecat_id, :active, :photo)
    end
end

app/helpers/animalcats_helper.rb
module AnimalcatsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articlecats_helper.rb
module ArticlecatsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coincidences_helper.rb
module CoincidencesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :article_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :article_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :article_price %>
  </div>

  <div class="field">
    <%= form.label :animal_id %>
    <%= form.number_field :animal_id, id: :article_animal_id %>
  </div>

  <div class="field">
    <%= form.label :articlecat_id %>
    <%= form.number_field :articlecat_id, id: :article_articlecat_id %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :article_active %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :article_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Animal</th>
      <th>Articlecat</th>
      <th>Active</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.description %></td>
        <td><%= article.price %></td>
        <td><%= article.animal_id %></td>
        <td><%= article.articlecat_id %></td>
        <td><%= article.active %></td>
        <td><%= article.photo %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @article.price %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @article.animal_id %>
</p>

<p>
  <strong>Articlecat:</strong>
  <%= @article.articlecat_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @article.active %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @article.photo %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>