config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :tests
  resources :answers
  resources :questions
  resources :coincidences
  resources :articles
  resources :animals
  resources :articlecats
  resources :animalcats
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
	has_many :coincidences
	belongs_to :animalcat 
	has_many :articles 
	has_many :tests
end

app/models/animalcat.rb
class Animalcat < ApplicationRecord
	has_many :animals
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	has_many :results
	has_many :tests, through: :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :animal
	belongs_to :articlecat
end

app/models/articlecat.rb
class Articlecat < ApplicationRecord
	has_many :articles
end

app/models/coincidence.rb
class Coincidence < ApplicationRecord
	belongs_to :animal
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :test
	belongs_to :answer
end

app/models/test.rb
class Test < ApplicationRecord
	belongs_to :animal
	belongs_to :user
	has_many :results
	has_many :answers, through: :results
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tests
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:test_id, :answer_id)
    end
end

app/helpers/animalcats_helper.rb
module AnimalcatsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articlecats_helper.rb
module ArticlecatsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coincidences_helper.rb
module CoincidencesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :test_id %>
    <%= form.number_field :test_id, id: :result_test_id %>
  </div>

  <div class="field">
    <%= form.label :answer_id %>
    <%= form.number_field :answer_id, id: :result_answer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th>Test</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.test_id %></td>
        <td><%= result.answer_id %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Test:</strong>
  <%= @result.test_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @result.answer_id %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>