config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :tests
  resources :answers
  resources :questions
  resources :coincidences
  resources :articles
  resources :animals
  resources :articlecats
  resources :animalcats
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
	has_many :coincidences
	belongs_to :animalcat 
	has_many :articles 
	has_many :tests
end

app/models/animalcat.rb
class Animalcat < ApplicationRecord
	has_many :animals
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	has_many :results
	has_many :tests, through: :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :animal
	belongs_to :articlecat
end

app/models/articlecat.rb
class Articlecat < ApplicationRecord
	has_many :articles
end

app/models/coincidence.rb
class Coincidence < ApplicationRecord
	belongs_to :animal
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :test
	belongs_to :answer
end

app/models/test.rb
class Test < ApplicationRecord
	belongs_to :animal
	belongs_to :user
	has_many :results
	has_many :answers, through: :results
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tests
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :answer, :active)
    end
end

app/helpers/animalcats_helper.rb
module AnimalcatsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articlecats_helper.rb
module ArticlecatsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coincidences_helper.rb
module CoincidencesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id, id: :answer_question_id %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, id: :answer_answer %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :answer_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.answer %></td>
        <td><%= answer.active %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<p>
  <strong>Active:</strong>
  <%= @answer.active %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>