config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :tests
  resources :answers
  resources :questions
  resources :coincidences
  resources :articles
  resources :animals
  resources :articlecats
  resources :animalcats
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
	has_many :coincidences
	belongs_to :animalcat 
	has_many :articles 
	has_many :tests
end

app/models/animalcat.rb
class Animalcat < ApplicationRecord
	has_many :animals
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	has_many :results
	has_many :tests, through: :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :animal
	belongs_to :articlecat
end

app/models/articlecat.rb
class Articlecat < ApplicationRecord
	has_many :articles
end

app/models/coincidence.rb
class Coincidence < ApplicationRecord
	belongs_to :animal
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :test
	belongs_to :answer
end

app/models/test.rb
class Test < ApplicationRecord
	belongs_to :animal
	belongs_to :user
	has_many :results
	has_many :answers, through: :results
end

app/models/user.rb
class User < ApplicationRecord
	has_many :tests
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :latinName, :weight, :size, :price, :description, :sex, :typeani, :observations, :linkfb, :animalcat_id, :active, :photo)
    end
end

app/helpers/animalcats_helper.rb
module AnimalcatsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articlecats_helper.rb
module ArticlecatsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coincidences_helper.rb
module CoincidencesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :animal_name %>
  </div>

  <div class="field">
    <%= form.label :latinName %>
    <%= form.text_field :latinName, id: :animal_latinName %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight, id: :animal_weight %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :animal_size %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :animal_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :animal_description %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex, id: :animal_sex %>
  </div>

  <div class="field">
    <%= form.label :typeani %>
    <%= form.number_field :typeani, id: :animal_typeani %>
  </div>

  <div class="field">
    <%= form.label :observations %>
    <%= form.text_field :observations, id: :animal_observations %>
  </div>

  <div class="field">
    <%= form.label :linkfb %>
    <%= form.text_field :linkfb, id: :animal_linkfb %>
  </div>

  <div class="field">
    <%= form.label :animalcat_id %>
    <%= form.number_field :animalcat_id, id: :animal_animalcat_id %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.number_field :active, id: :animal_active %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :animal_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latinname</th>
      <th>Weight</th>
      <th>Size</th>
      <th>Price</th>
      <th>Description</th>
      <th>Sex</th>
      <th>Typeani</th>
      <th>Observations</th>
      <th>Linkfb</th>
      <th>Animalcat</th>
      <th>Active</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.latinName %></td>
        <td><%= animal.weight %></td>
        <td><%= animal.size %></td>
        <td><%= animal.price %></td>
        <td><%= animal.description %></td>
        <td><%= animal.sex %></td>
        <td><%= animal.typeani %></td>
        <td><%= animal.observations %></td>
        <td><%= animal.linkfb %></td>
        <td><%= animal.animalcat_id %></td>
        <td><%= animal.active %></td>
        <td><%= animal.photo %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Latinname:</strong>
  <%= @animal.latinName %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @animal.weight %>
</p>

<p>
  <strong>Size:</strong>
  <%= @animal.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @animal.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @animal.description %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @animal.sex %>
</p>

<p>
  <strong>Typeani:</strong>
  <%= @animal.typeani %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @animal.observations %>
</p>

<p>
  <strong>Linkfb:</strong>
  <%= @animal.linkfb %>
</p>

<p>
  <strong>Animalcat:</strong>
  <%= @animal.animalcat_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @animal.active %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @animal.photo %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>